apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sns-deploy
  name: sns-deploy
  namespace: sns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sns-deploy
  template:
    metadata:
      labels:
        app: sns-deploy
    spec:
      containers:
      - image: philgman1121/sns-app
        name: sns-app
        ports:
        - containerPort: 5000
        env:
        - name: SNS_TOPIC_NAME
          value: "REPLACE_WITH_SNS_TOPIC_NAME"
        - name: AWS_DEFAULT_REGION
          value: "REPLACE_WITH_AWS_REGION"
