apiVersion: v1
kind: Service
metadata:
  labels:
    app: sns-deploy
  name: sns-deploy
  namespace: sns-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sns-deploy
  type: ClusterIP